---
name: build helix
run-name: build helix-${{inputs.version}}

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: version to build (without "v")
        default: "23.10"
        type: string

permissions: write-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {target: x86_64-unknown-linux-gnu, name: linux-amd64}
    name: Build ${{matrix.target}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Build
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          build-args: |
            VERSION=${{inputs.version}}
            TARGET=${{matrix.target}}
          outputs: type=local,dest=./dist

      - name: Upload ${{matrix.target}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          mv dist helix-v${{inputs.version}}-${{matrix.name}}
          tar -cJf "helix-v${{inputs.version}}-${{matrix.name}}.tar.xz" helix-v${{inputs.version}}-${{matrix.name}}
          # create release if not exist
          gh release create "v${{inputs.version}}" --notes "Release helix v${{inputs.version}}" --title "v${{inputs.version}}" --repo "${{github.repository}}" || true
          # delete the asset if exists
          gh release delete-asset "v${{inputs.version}}" "helix-v${{inputs.version}}-${{matrix.name}}.tar.xz" --yes --repo "${{github.repository}}" || true
          gh release upload "v${{inputs.version}}" "./helix-v${{inputs.version}}-${{matrix.name}}.tar.xz" --repo "${{github.repository}}"
