---
name: docker-manual
run-name: build ${{inputs.version}} via docker
env:
  upstream: helix-editor/helix

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: version to build (without "v")
        default: "23.10"
        type: string

permissions: write-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # - {target: aarch64-unknown-linux-gnu, platform: arm64}
          - {target: x86_64-unknown-linux-gnu, platform: amd64}

    name: Build ${{matrix.target}}
    runs-on: ubuntu-latest
    env:
      CARGO: cargo
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Checkout upstream
        uses: actions/checkout@main
        with:
          repository: ${{env.upstream}}
          ref: ${{inputs.version}}
          path: src

      - name: Delete rust-toolchain.toml
        run: |
          [ -f "src/rust-toolchain.toml" ] && rm src/rust-toolchain.toml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Build
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile
          platforms: linux/${{matrix.platform}}
          push: false
          build-args: |
            TARGET=${{matrix.target}}
          outputs: type=local,dest=./dist

      - name: Upload ${{matrix.target}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          mv dist helix-v${{inputs.version}}-${{matrix.target}}
          tar -cJf "helix-v${{inputs.version}}-${{matrix.target}}.tar.xz" helix-v${{inputs.version}}-${{matrix.target}}
          # create release if not exist
          gh release create "v${{inputs.version}}" --notes "Release helix v${{inputs.version}}" --title "v${{inputs.version}}" --repo "${{github.repository}}" || true
          # delete the asset if exists
          gh release delete-asset "v${{inputs.version}}" "helix-v${{inputs.version}}-${{matrix.target}}.tar.xz" --yes --repo "${{github.repository}}" || true
          gh release upload "v${{inputs.version}}" "./helix-v${{inputs.version}}-${{matrix.target}}.tar.xz" --repo "${{github.repository}}"
